# Generated by Django 2.1.7 on 2019-02-23 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Captcha',
            fields=[
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('secret', models.CharField(max_length=6)),
                ('created', models.DateTimeField(auto_now=True)),
                ('retries', models.PositiveSmallIntegerField(default=10)),
            ],
        ),
    ]
